### PR TITLE
Fix #78 by overloading promote_array_type

### LINKED ISSUE #78: Breaking change between v0.1.2 and v0.1.3
With the v0.1.2 I was able to do

```
x = randn(100)
function h(θ)
           m1 = θ[1] - x
           m2 = θ[2]^2 - (x - θ[1]).^2
           m3 = x.^3 - θ[1]*(θ[1]^2 + 3*θ[2]^2)
           return [m1 m2 m3]
       end

hh(theta) = vec(sum(h(theta), 1))

ForwardDiff.jacobian(hh, [.1, .1])
```

With the latest release (v.0.1.3) I get an error:

```
ERROR: InexactError()
 in setindex! at array.jl:313
 in .- at arraymath.jl:120
 in - at arraymath.jl:142
 in h at none:2
 in hh at none:1
 in _calc_jacobian at /Users/gragusa/.julia/v0.4/ForwardDiff/src/api/jacobian.jl:101
 in jacobian at /Users/gragusa/.julia/v0.4/ForwardDiff/src/api/jacobian.jl:27
```

I compared the release and does not seem to be any change that might have affected this. What am I missing?

### PR DESCRIPTION
**Pull request by gragusa**
This updated PR fix #78. The problem was due to `promote_array_type` not having methods for ForwardDiffNumber.

### CODE REVIEW

File: test/test_behaviors.jl [hunk 1]
```diff
@@ -48,3 +48,66 @@ j = x -> ForwardDiff.jacobian(g, x, chunk_size=2)/2 # jacobian in chunk_mode
...
+#######################
+
+# Test overloading of `promote_array_type`
+#-------------------------------------------------------#
+
+promtyp = Base.promote_array_type(Base.DotAddFun(),
+                                  ForwardDiff.ForwardDiffNumber{2, Float64,
+                                  Tuple{Float64, Float64}}, Float64)
+fdiffnum = ForwardDiff.ForwardDiffNumber{2,Float64,Tuple{Float64,Float64}}    
+@test promtyp <: fordiffnum
```
Comment (KristofferC) [inline test/test_behaviors.jl]: fdiffnum

Comment (gragusa) [inline test/test_behaviors.jl]: Yes, I just fixed it. Thanks.

**Comment by gragusa** [comment]
@jrevels This PR overload promote_array_type for ForwardDiff.

**Comment by jrevels** [comment]
Awesome, thanks for this! Let's wait for @mlubin's opinion, but this LGTM.

**Comment by mlubin** [comment]
LGTM
