### PR TITLE
Do not seed structural zeros

### LINKED ISSUE #738: UpperTriangular / LowerTriangular broken on 1.0.0
MWE:

```julia
using ForwardDiff, LinearAlgebra
ForwardDiff.gradient(sum, UpperTriangular(randn(3, 3)))
```

On v0.10.38

```julia
julia> ForwardDiff.gradient(sum, UpperTriangular(randn(3, 3)))
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  1.0
  ⋅   1.0  1.0
  ⋅    ⋅   1.0
```

On v1.0.0

```julia
julia> ForwardDiff.gradient(sum, UpperTriangular(randn(3, 3)))
ERROR: ArgumentError: cannot set index in the lower triangular part (2, 1) of an UpperTriangular matrix to a nonzero value (Dual{ForwardDiff.Tag{typeof(sum), Float64}}(0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0))
Stacktrace:
  [1] throw_nonzeroerror(T::Type, x::Any, i::Int64, j::Int64)
    @ LinearAlgebra ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/triangular.jl:295
  [2] setindex!
    @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/triangular.jl:306 [inlined]
  [3] _unsafe_setindex!
    @ ./reshapedarray.jl:297 [inlined]
  [4] setindex!
    @ ./reshapedarray.jl:286 [inlined]
  [5] setindex!
    @ ./subarray.jl:372 [inlined]
  [6] macro expansion
    @ ./broadcast.jl:973 [inlined]
  [7] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [8] copyto!
    @ ./broadcast.jl:972 [inlined]
  [9] copyto!
    @ ./broadcast.jl:925 [inlined]
 [10] materialize!
    @ ./broadcast.jl:883 [inlined]
 [11] materialize!
    @ ./broadcast.jl:880 [inlined]
 [12] seed!(duals::UpperTriangular{…}, x::UpperTriangular{…}, seeds::NTuple{…})
    @ ForwardDiff ~/ppl/ForwardDiff.jl/src/apiutils.jl:52
 [13] vector_mode_dual_eval!(f::typeof(sum), cfg::ForwardDiff.GradientConfig{…}, x::UpperTriangular{…})
    @ ForwardDiff ~/ppl/ForwardDiff.jl/src/apiutils.jl:23
 [14] vector_mode_gradient(f::typeof(sum), x::UpperTriangular{…}, cfg::ForwardDiff.GradientConfig{…})
    @ ForwardDiff ~/ppl/ForwardDiff.jl/src/gradient.jl:91
 [15] gradient
    @ ~/ppl/ForwardDiff.jl/src/gradient.jl:20 [inlined]
 [16] gradient(f::typeof(sum), x::UpperTriangular{…}, cfg::ForwardDiff.GradientConfig{…})
    @ ForwardDiff ~/ppl/ForwardDiff.jl/src/gradient.jl:17
 [17] gradient(f::typeof(sum), x::UpperTriangular{Float64, Matrix{Float64}})
    @ ForwardDiff ~/ppl/ForwardDiff.jl/src/gradient.jl:17
 [18] top-level scope
    @ REPL[2]:1
Some type information was truncated. Use `show(err)` to see complete types.
```

I think this is caused by #695 and the fact that `iszero(ForwardDiff.Dual(0.0, 1.0))` no longer returns true, so the checks here fail https://github.com/JuliaLang/LinearAlgebra.jl/blob/aecb71426201bad8447be446589d3af986886a87/src/triangular.jl#L295-L304

### PR DESCRIPTION
**Pull request by devmotion**
Fixes #738.

Since I had made https://github.com/JuliaDiff/ForwardDiff.jl/pull/695 I felt somewhat responsible for #738. Defining `seed!` and `extract_gradient!` for triangular matrices seems to fix the example.

Probably this should b extended to additional matrix types.

### CODE REVIEW

File: test/GradientTest.jl [hunk 1]
```diff
@@ -226,4 +226,13 @@ end
     @test dx ≈ sum(a * b)
 end
 
+# issue #738
+@testset "LowerTriangular and UpperTriangular" begin
+    M = rand(3, 3)
+    for T in (LowerTriangular, UpperTriangular)
+        @test ForwardDiff.gradient(sum, T(randn(3, 3))) == T(ones(3, 3))
```
Comment (mcabbott) [inline test/GradientTest.jl:233]: Unfortunately this fails if I increase the size of the matrix above the chunk size:
```julia
julia> @testset "LowerTriangular and UpperTriangular" begin
           M = rand(3, 3)
           for T in (LowerTriangular, UpperTriangular)
               @test ForwardDiff.gradient(sum, T(randn(3, 3))) == T(ones(3, 3))
               @test ForwardDiff.gradient(x -> dot(M, x), T(randn(3, 3))) == T(M)
           end
       end
Test Summary:                       | Pass  Total  Time
LowerTriangular and UpperTriangular |    4      4  1.0s
Test.DefaultTestSet("LowerTriangular and UpperTriangular", Any[], 4, false, false, true, 1.74360103628159e9, 1.743601037319704e9, false, "REPL[8]")

julia> @testset "LowerTriangular and UpperTriangular" begin
           M = rand(10, 10)
           for T in (LowerTriangular, UpperTriangular)
               @test ForwardDiff.gradient(sum, T(randn(10, 10))) == T(ones(10, 10))
               @test ForwardDiff.gradient(x -> dot(M, x), T(randn(10, 10))) == T(M)
           end
       end
LowerTriangular and UpperTriangular: Error During Test at REPL[9]:4
  Test threw exception
  Expression: ForwardDiff.gradient(sum, T(randn(10, 10))) == T(ones(10, 10))
  ArgumentError: cannot set index in the upper triangular part (1, 2) of an LowerTriangular matrix to a nonzero value (Dual{ForwardDiff.Tag{typeof(sum), Float64}}(0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0))
  Stacktrace:
    [1] throw_nonzeroerror(T::Type, x::Any, i::Int64, j::Int64)
      @ LinearAlgebra ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/triangular.jl:295
    [2] setindex!
      @ ~/.julia/juliaup/julia-1.11.4+0.aarch64.apple.darwin14/share/julia/stdlib/v1.11/LinearAlgebra/src/triangular.jl:326 [inlined]
    [3] _unsafe_setindex!
      @ ./reshapedarray.jl:297 [inlined]
    [4] setindex!
      @ ./reshapedarray.jl:286 [inlined]
    [5] setindex!
      @ ./subarray.jl:372 [inlined]
    [6] macro expansion
      @ ./broadcast.jl:973 [inlined]
    [7] macro expansion
      @ ./simdloop.jl:77 [inlined]
    [8] copyto!
      @ ./broadcast.jl:972 [inlined]
    [9] copyto!
      @ ./broadcast.jl:925 [inlined]
   [10] materialize!
      @ ./broadcast.jl:883 [inlined]
   [11] materialize!
      @ ./broadcast.jl:880 [inlined]
   [12] seed!(duals::LowerTriangular{ForwardDiff.Dual{ForwardDiff.Tag{typeof(sum), Float64}, Float64, 12}, Matrix{ForwardDiff.Dual{ForwardDiff.Tag{typeof(sum), Float64}, Float64, 12}}}, x::LowerTriangular{Float64, Matrix{Float64}}, index::Int64, seeds::NTuple{12, ForwardDiff.Partials{12, Float64}}, chunksize::Int64)
      @ ForwardDiff ~/.julia/packages/ForwardDiff/L0kjR/src/apiutils.jl:69
   [13] seed!
      @ ~/.julia/packages/ForwardDiff/L0kjR/src/apiutils.jl:66 [inlined]
   [14] chunk_mode_gradient(f::typeof(sum), x::LowerTriangular{Float64, Matrix{Float64}}, cfg::ForwardDiff.GradientConfig{ForwardDiff.Tag{typeof(sum), Float64}, Float64, 12, LowerTriangular{ForwardDiff.Dual{ForwardDiff.Tag{typeof(sum), Float64}, Float64, 12}, Matrix{ForwardDiff.Dual{ForwardDiff.Tag{typeof(sum), Float64}, Float64, 12}}}})
```

Comment (devmotion) [reply test/GradientTest.jl:233]: Ah good catch 👍

Comment (devmotion) [reply test/GradientTest.jl:233]: Another catch is: This PR doesn't (yet) fix the fact that still for every element of the matrices seeds are generated - even though (IMO) we should limit it to the structurally non-zero entries.

Comment (mcabbott) [reply test/GradientTest.jl]: I have forgotten how all this code works... but 5-arg `seed!` implies the iteration is happening elsewhere?

The other thing worth checking would be GradientConfig and DiffResult things from https://juliadiff.org/ForwardDiff.jl/stable/user/advanced/ as I'm not sure what paths they take.

Comment (devmotion) [reply test/GradientTest.jl]: Yeah, `seed!` (and `extract_gradient!`) with > 3 arguments are called if gradients are computed in multiple chunks: https://github.com/JuliaDiff/ForwardDiff.jl/blob/fd2d4a98b7fc9bb965d98084b0152382898d3c04/src/gradient.jl#L118-L142

Comment (devmotion) [reply test/GradientTest.jl]: In the end, everything takes the `GradientConfig` path - if you don't provide one, ForwardDiff sets one up as `GradientConfig(f, x)` (IIRC).

Comment (mcabbott) [reply test/GradientTest.jl]: Ah that sounds right.

Something curious on the latest commit -- chunk size 6 is all it needs, but it still calls it twice?
```julia
julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, UpperTriangular(rand(3,3)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#7#8", Float64}, Float64, 6}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#7#8", Float64}, Float64, 6}
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  1.0
  ⋅   1.0  1.0
  ⋅    ⋅   1.0

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(3,3)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#9#10", Float64}, Float64, 3}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#9#10", Float64}, Float64, 3}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#9#10", Float64}, Float64, 3}
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
```
Compare v0.10:
```
julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, UpperTriangular(rand(3,3)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#73#74", Float64}, Float64, 9}
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  1.0
  ⋅   1.0  1.0
  ⋅    ⋅   1.0

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(3,3)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#75#76", Float64}, Float64, 9}
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
```

Comment (devmotion) [reply test/GradientTest.jl]: Sure, we have to update the gradient function (where these are called) as well, otherwise a smaller chunksize just means that it's called more often.

Comment (devmotion) [reply test/GradientTest.jl]: With https://github.com/JuliaDiff/ForwardDiff.jl/pull/739/commits/161d227711a1501686b82d38063b7a121a23bf00 I get

```julia
julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, UpperTriangular(rand(3,3)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#25#26", Float64}, Float64, 6}
3×3 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  1.0
  ⋅   1.0  1.0
  ⋅    ⋅   1.0

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(3,3)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#27#28", Float64}, Float64, 3}
3×3 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅    ⋅ 
  ⋅   1.0   ⋅ 
  ⋅    ⋅   1.0
```

(but I assume it broke a few other things, let's see...)

Comment (mcabbott) [reply test/GradientTest.jl]: Those look good. Some chance this is flawed copy-pasting at my end, but for chunk mode I see strange effects:
```julia
julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, UpperTriangular(rand(5, 5)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#27#28", Float64}, Float64, 8}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#27#28", Float64}, Float64, 8}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#27#28", Float64}, Float64, 8}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#27#28", Float64}, Float64, 8}
5×5 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  1.0  1.0  1.0
  ⋅   1.0  1.0  1.0  1.0
  ⋅    ⋅   1.0  1.0  1.0
  ⋅    ⋅    ⋅   1.0  1.0
  ⋅    ⋅    ⋅    ⋅   1.0

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(11)));  # ok
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#21#22", Float64}, Float64, 11}

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(13)));  # weird
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#23#24", Float64}, Float64, 7}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#23#24", Float64}, Float64, 7}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#23#24", Float64}, Float64, 7}
[.... >15 more]
```

Comment (devmotion) [reply test/GradientTest.jl]: Hmm, strange. I get
```julia
julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, UpperTriangular(rand(5, 5)))
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#40#41", Float64}, Float64, 8}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#40#41", Float64}, Float64, 8}
5×5 UpperTriangular{Float64, Matrix{Float64}}:
 1.0  1.0  1.0  1.0  1.0
  ⋅   1.0  1.0  1.0  1.0
  ⋅    ⋅   1.0  1.0  1.0
  ⋅    ⋅    ⋅   1.0  1.0
  ⋅    ⋅    ⋅    ⋅   1.0

julia> sum(ans)
15.0

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(11)));
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#42#43", Float64}, Float64, 11}

julia> ForwardDiff.gradient(x -> begin @show(eltype(x)); sum(x) end, Diagonal(rand(13)));
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#44#45", Float64}, Float64, 7}
eltype(x) = ForwardDiff.Dual{ForwardDiff.Tag{var"#44#45", Float64}, Float64, 7}
```
which seems expected given https://github.com/JuliaDiff/ForwardDiff.jl/blob/fd2d4a98b7fc9bb965d98084b0152382898d3c04/src/prelude.jl#L10-L13

Comment (devmotion) [reply test/GradientTest.jl]: The only test failures are the ones already present on the master branch (possibly related to some recent changes of acosh or NaNMath.acosh?).

**Review by mcabbott — APPROVED** [review]

File: test/GradientTest.jl (hunk 1 above)
Comment (mcabbott) [reply test/GradientTest.jl]: My weird results above must have been my mistake, lazy to check out the branch... 

We could add tests of how many executions are used in chunk mode (not sure whether there are any such now) but not essential.

Comment (devmotion) [reply test/GradientTest.jl]: I added a test in https://github.com/JuliaDiff/ForwardDiff.jl/pull/739/commits/d2a8af7eaa9c43820c686f2abc9384de129da96f.
